name = "cyrus-proxy"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# KV namespaces
[[kv_namespaces]]
binding = "OAUTH_TOKENS"
id = "42a25ed26da242999cd4c65606d49adc"
#preview_id = "ec053da0c66040c9816a5941c6a7962d"

[[kv_namespaces]]
binding = "OAUTH_STATE"
id = "717458ac0b114aa594643844b70d1d2a"
#preview_id = "6c441400d54f41e3bc80b9257f2fe59e"

[[kv_namespaces]]
binding = "EDGE_TOKENS"
id = "cfd4d48d80004948ae78408de68acec9"
#preview_id = "fe6413e4f7484d3997d00fcb06c40f8f"

[[kv_namespaces]]
binding = "WORKSPACE_METADATA"
id = "9b932d477d034ca7a47cc32d7e64ff85"
#preview_id = "48028e79310949ea98dbbbe49292a28e"


# Environment variables (use wrangler secret for production)
[vars]
OAUTH_REDIRECT_URI = "https://cyrus-proxy.pidof.workers.dev/oauth/callback"

